# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: essmqtt add-on
version: "1.2.0"
slug: essmqtt_addon
description: essmqtt addon add-on
url: "https://github.com/gluap/pyess-addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  ess_host: "127.0.0.1"
  ess_password: "ess_password"
  ess_sensors: "ess/common/BATT/soc,ess/home/statistics/pcs_pv_total_power,ess/common/GRID/active_power,ess/common/LOAD/load_power,ess/common/PCS/month_pv_generation_sum,ess/common/PCS/month_grid_feed_in_energy,ess/home/statistics/batconv_power,ess/common/BATT/month_batt_charge_energy,ess/common/BATT/month_batt_discharge_energy,ess/common/GRID/month_grid_power_purchase_energy,ess/control/active"
schema:
  ess_host: "str?"
  ess_password: "str?"
  ess_sensors: "str?"
services:
  - "mqtt:need"
image: "ghcr.io/gluap/{arch}-pyess-addon"
