# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: essmqtt add-on
version: "1.2.0"
slug: essmqtt_addon
description: essmqtt addon add-on
url: "https://github.com/gluap/pyess-addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
