# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: pyess add-on
version: "0.0.2"
slug: pyess-addon
description: pyess/essmqtt add-on
url: "https://github.com/SIMULATAN/pyess-addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  watchdog:
    restart_wait: 10
  inverters:
    - ess_name: myess
      ess_host: "127.0.0.1"
      ess_password: "ess_password"
      ess_sensors: "common/BATT/soc,home/statistics/pcs_pv_total_power,common/GRID/active_power,common/LOAD/load_power,common/PCS/month_pv_generation_sum,common/PCS/month_grid_feed_in_energy,home/statistics/batconv_power,common/BATT/month_batt_charge_energy,common/BATT/month_batt_discharge_energy,common/GRID/month_grid_power_purchase_energy,control/active"
      ess_update_interval: 10

schema:
  watchdog:
    restart_wait: "int(1,600)?"
  inverters:
    - ess_name: "str"
      ess_host: "str"
      ess_password: "str"
      ess_sensors: "str?"
      ess_update_interval: "int(1,600)?"
services:
  - "mqtt:need"
# image: "ghcr.io/simulatan/pyess-addon-{arch}"
